### ISSUE TITLE
'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by 21adrian1996** [mosparo/django-integration#4]
Using mosparo in a form which has only fields which are ignored in ignored_field_types the form returns the following error:

`AttributeError at {URL} 'list' object has no attribute 'keys'`

The error seems to happen in https://github.com/mosparo/django-integration/blob/81b64b94a0be700b90740892c02321689e099b51/mosparo_django/fields.py#L81 
because it returns an empty list instead of an empty dict, so `verified_fields  = []` and therfore `verified_fields.keys()` fails on the next line

**Comment by zepich** [comment]
Hi @21adrian1996 

Thank you very much for your report.

I've tested this case myself and can reproduce the issue. The problem is that PHP in mosparo outputs an empty associative array as an array (`[]`) instead of an object (`{}`). Python then converts the empty array to a list object, which was accidentally returned instead of a dict.

I've added a fix for that and released v1.1.2. The method now returns an empty dict instead of a list.

Thank you for your help in making mosparo better!

Kind regards,

zepich
